name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Npm install
        run: make install

      - name: install babel-eslint
        run: npm install eslint babel-eslint --save-dev
        
      - name: Lint Files
        run: make lint

      - name: Run test
        run: make test
