name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Npm install
        run: npm install

      - name: Run test
        run: make test

      - name: Lint Files
        run: node Makefile lint
